package assignment;
// DO NOT EDIT THIS FILE
public class Heuristic {

	/*
	 * A simple class representing heuristic estimates to a goal.

	 * The instance field distsToGoal represents the estimated 
	 * distances from each node to the goal.
	 */
	private double[] distsToGoal;
	/*
	 * The Heuristic constructor takes a goal node, and a two-dimensional array, 
	 * where the i_th array represents the estimated distance from each node to
	 * node i. 
	 */
	public Heuristic(int goal, double[][] estimates)
	{		
		// distsToGoal now contains an array of estimates from
		// each node to the provided goal node.
		distsToGoal = estimates[goal];
	}
	/*
	 * Estimate the distance from a given node to the goal.
	 */
	public double estimate(int node)
	{
		return distsToGoal[node];
	}
}

