package assignment;
// DO NOT EDIT THIS FILE
public class NodeRecord implements Comparable<NodeRecord>{

	/**
	 * A simple class for keeping track of information about each node 
	 * during the search process.
	 * Note that NodeRecords are sortable by estimatedTotalCost 
	 * (the class implements Comparable).
	 */
	
	
	/*
	 * Ordinarily instance fields should be private,
	 * but we are treating NodeRecord as a simple struct
	 * to simplify the rest of the code.
	 * There are no getters or setters for NodeRecord since
	 * the fields can be accessed and set directly.
	 */	
	public int node;
	public Arc arc;
	public double costSoFar;
	public double estimatedTotalCost;
	
	
	/*
	 * NodeRecords are sorted according to estimatedTotalCost.
	 * The compareTo() method is used to sort any two NodeRecords.
	 * 
	 */
	public int compareTo(NodeRecord other)
	{
		if (estimatedTotalCost < other.estimatedTotalCost) return -1;
		if (estimatedTotalCost == other.estimatedTotalCost) return 0;
		return 1;
	}
	
	
	// A simple String representation of a NodeRecord.
	public String toString()
	{
		return node + " "+arc;
	}
	
}

