package aStar;
// DO NOT EDIT THIS FILE
public class Arc {

	/*
	 * A class for storing information about arcs/edges between nodes.
	 * Note that these arcs are simply stored and looked up,
	 * rather than processed during search.
	 * 
	 * Each Arc is associated with a cost.
	 */
	private double cost;
	private int fromNode;
	private int toNode;
	
	public Arc(double cost, int fromNode, int toNode)
	{
		this.cost = cost;
		this.fromNode = fromNode;
		this.toNode = toNode;
	}
	
	// returns the non-negative cost of the Arc
	public double getCost() {return cost;}
	
	// return the node that this Arc came from
	public int getFromNode() {return fromNode;}
	
	// returns the node that this Arc leads to
	public int getToNode() {return toNode;}

	// simply a String representation of the Arc
	public String toString()
	{
		return fromNode + " to " +toNode;
	}
}

